const data = [
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18, 10402, 10749, 10770],
        id: 402804,
        original_language: "it",
        original_title: "Notre Dame de Paris - Live Arena di Verona",
        overview:
          "Notre Dame de Paris tells the story of Quasimodo, the hunchbacked bell-ringer of the cathedral of Notre-Dame and of his impossible and tragic love for Esmeralda, a beautiful gypsy. A love condemned by injustice and hypocrisy. Quasimodo forced by his ugliness to look at the world from the top of a tower one day he falls madly in love with Esmeralda who sees dancing and singing on the square in front of the cathedral. But Esmeralda is in love with Febo, the handsome captain of the King's guards. Febo is fiancé of Fiordaliso, a young and rich bourgeois, but the exotic and sensual beauty of the gypsy does not leave indifferent the man who immediately falls in love with her. Even Frollo, the archdeacon of the cathedral, is attracted by the gypsy and spying on the moves of the two lovers in a raptus of jealousy and repressed carnal desire to get rid of the rival stabbing Febo behind.",
        popularity: 1.355,
        poster_path: null,
        release_date: "2002-09-04",
        title: "Notre Dame de Paris - Live Arena di Verona",
        video: false,
        vote_average: 9.5,
        vote_count: 13,
      },
      {
        adult: false,
        backdrop_path: "/umjwd0vRZcQJ9Uzm7BMAT6bhZJ7.jpg",
        genre_ids: [18],
        id: 527436,
        original_language: "ko",
        original_title: "허스토리",
        overview:
          "A true story of a six-year-long legal conflict of 10 comfort women and 13 attorneys against 200 Fukuoka supporters association.",
        popularity: 2.457,
        poster_path: "/glMIRwo6RKzNaZBRQoWyj8x8fvI.jpg",
        release_date: "2018-06-27",
        title: "Herstory",
        video: false,
        vote_average: 9.4,
        vote_count: 10,
      },
      {
        adult: false,
        backdrop_path: "/PpAlok2zabLtSpleN6u8oMp7CV.jpg",
        genre_ids: [18],
        id: 373001,
        original_language: "es",
        original_title: "El Cementerio de los Elefantes",
        overview: "",
        popularity: 1.734,
        poster_path: "/r4AoFwoAYP1OBJAbmFTgUjGjAUE.jpg",
        release_date: "2009-08-24",
        title: "El Cementerio de los Elefantes",
        video: false,
        vote_average: 9.3,
        vote_count: 32,
      },
      {
        adult: false,
        backdrop_path: "/3h2BxJPIwrPoHRzz0RRt8RVHoFs.jpg",
        genre_ids: [18],
        id: 591322,
        original_language: "ko",
        original_title: "어린 의뢰인",
        overview:
          "A success-hungry lawyer meets a young sister and brother suffering from domestic abuse and digs into their case.",
        popularity: 5.85,
        poster_path: "/fwlzWOfZ5WptFUPuqJ8kJkHC8cN.jpg",
        release_date: "2019-05-22",
        title: "My First Client",
        video: false,
        vote_average: 9.2,
        vote_count: 45,
      },
      {
        adult: false,
        backdrop_path: "/xouU3elO5Zi9TH9KfrepQiorMyE.jpg",
        genre_ids: [28, 18],
        id: 790249,
        original_language: "en",
        original_title: "WWE Royal Rumble 2021",
        overview:
          "The annual beginning of the Road to WrestleMania will feature Drew McIntyre defending his WWE Championship against Goldberg, Kevin Owens facing \"The Head of the Table\" Roman Reigns in a Last Man Standing Match for the Universal Championship, and of course, the annual Men's and Women's Royal Rumble Matches that will determine who will headline the Showcase of the Immortals.",
        popularity: 8.123,
        poster_path: "/qfEfLwa4fMIDvPeGaJxAyaYHkmr.jpg",
        release_date: "2021-01-31",
        title: "WWE Royal Rumble 2021",
        video: false,
        vote_average: 9.1,
        vote_count: 48,
      },
      {
        adult: false,
        backdrop_path: "/zadFl8HjZkEl0UVFYDpAb1ZtuxF.jpg",
        genre_ids: [14, 16, 18],
        id: 637663,
        original_language: "en",
        original_title: "DC Showcase: Death",
        overview:
          "Vincent, an artist with unresolved inner demons, meets a mysterious girl who helps him come to terms with his creative legacy… and eventual death.",
        popularity: 13.793,
        poster_path: "/yuho3nB3YSdVS7DDge7yJ6VfU9e.jpg",
        release_date: "2019-10-22",
        title: "DC Showcase: Death",
        video: false,
        vote_average: 9.1,
        vote_count: 41,
      },
      {
        adult: false,
        backdrop_path: "/vX9FALAhEx3OyJN9mbHBMVaQNQA.jpg",
        genre_ids: [99, 80, 18],
        id: 637113,
        original_language: "en",
        original_title: "Square One: Michael Jackson",
        overview:
          "An investigation into the original 1993 Michael Jackson allegations brought by the Chandler family.",
        popularity: 11.04,
        poster_path: "/sVsAd5QoMbzEBt2U3WnzwAGD0dU.jpg",
        release_date: "2019-10-05",
        title: "Square One",
        video: false,
        vote_average: 9,
        vote_count: 34,
      },
      {
        adult: false,
        backdrop_path: "/pcJ4CcixagF4cAdUYuhjhyBRhqK.jpg",
        genre_ids: [18, 35],
        id: 570511,
        original_language: "ko",
        original_title: "힘을 내요, 미스터 리",
        overview:
          "Chul-soo is a man with an intellectual disability.  One day, Chul-soo finds out that a young girl, Saet-byul, who is in hospital is his daughter.  And soon, Saet-byul sneaks out of the hospital and travels by herself to a faraway city for her friend's birthday.  As Chul-soo accompanies Saet-byul's journey, friendship develops between the two.",
        popularity: 3.821,
        poster_path: "/ajV92rMweFHlQdgB0ushIx7sCMo.jpg",
        release_date: "2019-09-11",
        title: "Cheer Up, Mr. Lee",
        video: false,
        vote_average: 9,
        vote_count: 11,
      },
      {
        adult: false,
        backdrop_path: "/3z3JzKwqTfUTAiPlXH6BHFZeTNH.jpg",
        genre_ids: [35, 18],
        id: 486646,
        original_language: "it",
        original_title: "Natale in casa Cupiello",
        overview:
          "Luca Cupiello, like every Christmas, prepares the crib, amid the disinterest of his wife Concetta and his son Tommasino. Ninuccia, the other daughter, writes a letter to her husband in which she communicates that she leaves him for her lover. The letter happens in the hands of Luca who hands it over to his son-in-law, who thus learns of his wife's betrayal. During lunch on Christmas Eve, the two rivals, who were confronted by Luca's carelessness, clash violently.",
        popularity: 1.217,
        poster_path: "/fCq3KHKWWxbl69aCSS2k6HkmgiG.jpg",
        release_date: "1977-12-24",
        title: "Natale in casa Cupiello",
        video: false,
        vote_average: 9,
        vote_count: 32,
      },
      {
        adult: false,
        backdrop_path: "/u1wHUA0R48FH4WV3sGqjwx3aNZm.jpg",
        genre_ids: [16, 18, 10402, 10749],
        id: 632632,
        original_language: "ja",
        original_title: "映画 ギヴン",
        overview:
          "The film centers on the love relationship among the band's bassist Haruki Nakayama, drummer Akihiko Kaji, and Akihiko's roommate and ex-boyfriend Ugetsu Murata.",
        popularity: 286.058,
        poster_path: "/xKCtoYHUyX8zAg68eemnYa2orep.jpg",
        release_date: "2020-08-22",
        title: "Given",
        video: false,
        vote_average: 8.9,
        vote_count: 118,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18],
        id: 450015,
        original_language: "en",
        original_title: "20 Seconds of Courage",
        overview:
          'Five boys and girls. Five small courage. Five different stories. But all linked together.  From acclaimed director/writer Shunsuke Okubo ("Clocks Tell the Time" and "Moments")',
        popularity: 1.638,
        poster_path: "/wyqlEhwZoDwAjumeStNI2HhTDlV.jpg",
        release_date: "2016-04-15",
        title: "20 Seconds of Courage",
        video: false,
        vote_average: 8.8,
        vote_count: 10,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18, 10770],
        id: 348756,
        original_language: "es",
        original_title: "Doce hombres sin piedad",
        overview:
          "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young man is guilty or innocent of murdering his father.",
        popularity: 1.033,
        poster_path: "/bLLLaCxXsjX6dF2UfQApOGNsnu1.jpg",
        release_date: "1973-03-16",
        title: "Doce hombres sin piedad",
        video: false,
        vote_average: 8.8,
        vote_count: 13,
      },
      {
        adult: false,
        backdrop_path: "/xRI636TOdS1K1GBqIBRSmfZ1T5x.jpg",
        genre_ids: [35, 18, 10749],
        id: 19404,
        original_language: "hi",
        original_title: "दिलवाले दुल्हनिया ले जायेंगे",
        overview:
          "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
        popularity: 19.428,
        poster_path: "/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
        release_date: "1995-10-20",
        title: "Dilwale Dulhania Le Jayenge",
        video: false,
        vote_average: 8.8,
        vote_count: 2699,
      },
      {
        adult: false,
        backdrop_path: "/7prYzufdIOy1KCTZKVWpjBFqqNr.jpg",
        genre_ids: [16, 12, 14, 10751, 28, 18],
        id: 527774,
        original_language: "en",
        original_title: "Raya and the Last Dragon",
        overview:
          "Long ago, in the fantasy world of Kumandra, humans and dragons lived together in harmony. But when an evil force threatened the land, the dragons sacrificed themselves to save humanity. Now, 500 years later, that same evil has returned and it’s up to a lone warrior, Raya, to track down the legendary last dragon to restore the fractured land and its divided people.",
        popularity: 2440.581,
        poster_path: "/lPsD10PP4rgUGiGR4CCXA6iY0QQ.jpg",
        release_date: "2021-03-03",
        title: "Raya and the Last Dragon",
        video: false,
        vote_average: 8.7,
        vote_count: 647,
      },
      {
        adult: false,
        backdrop_path: "/AnCGi8vqK6kmyWAodt5aq5Y41g6.jpg",
        genre_ids: [35, 18],
        id: 156031,
        original_language: "pt",
        original_title: "Doce de Mãe",
        overview:
          "The story of Picucha, a 85-year-old suburban widow and mother of four who faces the reality of living alone in her age while keeping good humor and love for family and life.",
        popularity: 0.804,
        poster_path: null,
        release_date: "2012-12-27",
        title: "Doce de Mãe",
        video: false,
        vote_average: 8.7,
        vote_count: 13,
      },
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [18, 53],
        id: 795583,
        original_language: "es",
        original_title: "Vidas violentas",
        overview: "",
        popularity: 0.6,
        poster_path: "/76lwHLYYqzcsnCS31cR5ZFrrnwV.jpg",
        release_date: "2015-07-14",
        title: "Vidas violentas",
        video: false,
        vote_average: 8.7,
        vote_count: 11,
      },
      {
        adult: false,
        backdrop_path: "/tXHpvlr5F7gV5DwgS7M5HBrUi2C.jpg",
        genre_ids: [18, 80],
        id: 278,
        original_language: "en",
        original_title: "The Shawshank Redemption",
        overview:
          "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
        popularity: 41.778,
        poster_path: "/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
        release_date: "1994-09-23",
        title: "The Shawshank Redemption",
        video: false,
        vote_average: 8.7,
        vote_count: 18469,
      },
      {
        adult: false,
        backdrop_path: "/sTv1mRe8bLbMnGHpMignDWQCazI.jpg",
        genre_ids: [35, 18],
        id: 455502,
        original_language: "es",
        original_title: "Mi socio",
        overview:
          "The story of an improbable friendship and a social comment on life in Bolivia in the eighties.",
        popularity: 1.902,
        poster_path: "/8tuaTC6pMI6mjWLeei8JHk5TeF3.jpg",
        release_date: "1982-04-30",
        title: "My Partner",
        video: false,
        vote_average: 8.7,
        vote_count: 22,
      },
      {
        adult: false,
        backdrop_path: "/ke69su2Q4InbXgkvXxFwjaIVOWr.jpg",
        genre_ids: [18],
        id: 654387,
        original_language: "el",
        original_title: "Ευτυχία",
        overview:
          "A biographical film about the life of the greatest songwriter in Greece , Eftyhia Papagianopoulou (1893-1972)",
        popularity: 2.191,
        poster_path: "/ij5qH1EDViEGwSvc4dZLVPaKGLg.jpg",
        release_date: "2019-12-19",
        title: "Eftihia",
        video: false,
        vote_average: 8.7,
        vote_count: 18,
      },
      {
        adult: false,
        backdrop_path: "/wK8J98duAOa3QLIVMGIEZdjhgEK.jpg",
        genre_ids: [18],
        id: 627958,
        original_language: "pl",
        original_title: "Proceder",
        overview:
          "A Polish language biographical drama about the rapper Tomasz Chada.",
        popularity: 2.383,
        poster_path: "/4tNXOsfoNVJ0BCr3w6cJKSrL6eY.jpg",
        release_date: "2019-11-29",
        title: "Proceder",
        video: false,
        vote_average: 8.7,
        vote_count: 21,
      },
];

export default data;
